import Head from 'next/head'
import Banner from '../components/banner';
import Card from '../components/card';
import styles from '../styles/Home.module.css'
import Image from 'next/dist/client/image';
import coffeeStoresData from "../data/coffee-stores.json";
import { fetchCoffeeStores } from '../lib/coffee-stores';


//server side
export async function getStaticProps(context) {
  console.log('getStaticProps');

  const coffeeStores = await fetchCoffeeStores();

  return {
    props: {
      coffeeStores: coffeeStores,
    },
  }; // will be passed to the page as props
};

export default function Home(props) {
  console.log('props', props);
  const handleOnBannerBtnClick = () => {
    console.log('Hi banner button');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
          <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick}/>
          <div className={styles.heroImage}>
            <Image src="/static/hero-image.png" alt="A lady drinking coffee" width={700} height={400} />
          </div>
          {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Tooting stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
              // eslint-disable-next-line react/jsx-key
                <Card 
                key={coffeeStore.id} 
                name={coffeeStore.name} 
                imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80"}
                href={`/coffee-store/${coffeeStore.id}`} 
                className={styles.card}/>
              );
            })}
            </div>
          </>
        )}
        </main>
    </div>
  );
};


